"""init

Revision ID: 1f3e25c6a5f1
Revises: 
Create Date: 2026-03-13 17:43:39.733463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '1f3e25c6a5f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('total_attempted', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_metadata_id'), 'embedding_metadata', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_number', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('series', sa.Text(), nullable=True),
    sa.Column('processor', sa.Text(), nullable=True),
    sa.Column('ram', sa.Text(), nullable=True),
    sa.Column('storage', sa.Text(), nullable=True),
    sa.Column('screen_size', sa.Text(), nullable=True),
    sa.Column('graphic_processor', sa.Text(), nullable=True),
    sa.Column('colour', sa.Text(), nullable=True),
    sa.Column('embedding_status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='embedding_status'), nullable=False),
    sa.Column('embedded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_number')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('scraping_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('total_products_attempted', sa.Integer(), nullable=True),
    sa.Column('valid_products', sa.Integer(), nullable=True),
    sa.Column('invalid_products', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_fallback_run', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_metadata_id'), 'scraping_metadata', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='user_role'), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('is_refresh_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('activity_type', postgresql.ENUM('FIELD_MISSING', 'PRODUCT_NOT_FOUND', 'REDIRECTED', 'ALREADY_EXIST', name='activity_type_enum'), nullable=False),
    sa.Column('product_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('human_review_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['scraping_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('product_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('source', postgresql.ENUM('AMAZON', 'FLIPKART', name='listing_source'), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scraping_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'source', name='product_details_product_id_source_key')
    )
    op.create_index(op.f('ix_product_details_id'), 'product_details', ['id'], unique=False)
    op.create_table('product_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_metadata_id', sa.Uuid(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['embedding_metadata_id'], ['embedding_metadata.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_embeddings_id'), 'product_embeddings', ['id'], unique=False)
    op.create_index('product_embeddings_embedding_hnsw_idx', 'product_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_embeddings_embedding_hnsw_idx', table_name='product_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_product_embeddings_id'), table_name='product_embeddings')
    op.drop_table('product_embeddings')
    op.drop_index(op.f('ix_product_details_id'), table_name='product_details')
    op.drop_table('product_details')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scraping_metadata_id'), table_name='scraping_metadata')
    op.drop_table('scraping_metadata')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_embedding_metadata_id'), table_name='embedding_metadata')
    op.drop_table('embedding_metadata')
    # ### end Alembic commands ###
